version: '3'
services:
  www:

    volumes:
      - .:/opt/app/
    ports:
      - '80:80'
    build:
      context: .

  mongodb:
    image: mongo
    volumes:
      - /opt/app/db/:/data/db
    expose:
      - 27017

